blueprint:
  name: Temperature-Based Control
  description: Turn a device on/off based on a temperature threshold
  domain: automation
  input:
    temp_sensor:
      name: Temperature Sensor
      selector:
        entity:
          domain: sensor
          device_class: temperature
    target_entity:
      name: Target Entity
      selector:
        entity:
    min_temp:
      name: Minimum Temperature (°C)
      default: 18
      selector:
        number:
          min: 0
          max: 40
          step: 0.5
    max_temp:
      name: Maximum Temperature (°C)
      default: 22
      selector:
        number:
          min: 0
          max: 50
          step: 0.5

automation:
  trigger:
    - platform: state
      entity_id: !input temp_sensor
  condition: []
  action:
    - choose:
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor
              below: !input min_temp
          sequence:
            - service: switch.turn_on
              target:
                entity_id: !input target_entity
        - conditions:
            - condition: numeric_state
              entity_id: !input temp_sensor
              above: !input max_temp
          sequence:
            - service: switch.turn_off
              target:
                entity_id: !input target_entity