blueprint:
  name: Time-Based Schedule
  description: Turn a device on and off based on time of day
  domain: automation
  input:
    target_entity:
      name: Target Entity
      selector:
        entity:
          domain: switch
    powertarget_entity:
      name: Power Target Entity (number)
      selector:
        entity:
          domain: number
    start_time:
      name: Start Time
      selector:
        time:
    end_time:
      name: End Time
      selector:
        time:
    heating_level:
      name: Heater level
      selector:
        number:
          min: 1
          max: 5
          step: 1

trigger:
  - platform: time
    at: !input start_time
  - platform: time
    at: !input end_time
condition: []
action:
  - choose:
      - conditions:
          - condition: time
            after: !input start_time
            before: !input end_time
        sequence:
          - service: switch.turn_on
            target:
              entity_id: !input target_entity
          - service: number.set_value
            target:
              entity_id: !input powertarget_entity
            data:
              value: !input heating_level
      - conditions:
          - condition: or
            conditions:
              - condition: time
                before: !input start_time
              - condition: time
                after: !input end_time
        sequence:
          - service: switch.turn_off
            target:
              entity_id: !input target_entity
